### ISSUE TITLE
JSONDecodeError при использовании topup

### ISSUE THREAD

**Issue by hadrizi** [antidasoftware/cloudpayments-python-client#15]
Мне надо использовать метод `topup` для выплаты по токену, однако метод `_send_request` выкидывает исключение при попытке декодировать `response`

Ниже приведена _ошибка_
```
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1  |     response = self.process_exception_by_middleware(e, request)
web_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1  |     return view_func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
web_1  |     return self.dispatch(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
web_1  |     response = self.handle_exception(exc)
web_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1  |     self.raise_uncaught_exception(exc)
web_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1  |     raise exc
web_1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
web_1  |     response = handler(request, *args, **kwargs)
web_1  |   File "/code/apps/payment/api/viewsets.py", line 103, in pay_user
web_1  |     transaction = self.client.topup(token=token,
web_1  |   File "/usr/local/lib/python3.8/site-packages/cloudpayments/client.py", line 167, in topup
web_1  |     response = self._send_request('payments/cards/topup', params)
web_1  |   File "/usr/local/lib/python3.8/site-packages/cloudpayments/client.py", line 22, in _send_request
web_1  |     return response.json(parse_float=decimal.Decimal)
web_1  |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
web_1  |     return complexjson.loads(self.text, **kwargs)
web_1  |   File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 542, in loads
web_1  |     return cls(encoding=encoding, **kw).decode(s)
web_1  |   File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
web_1  |     obj, end = self.raw_decode(s)
web_1  |   File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
web_1  |     return self.scan_once(s, idx=_w(s, idx).end())
web_1  | simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Ниже приведен _мой_ код
```
token = serializer_topup.validated_data['token']
transaction = self.client.topup(token=token, amount=to_pay, account_id="user_"+str(request.user.id), currency="RUB")
```

**Comment by hadrizi** [comment]
Проблема решена
